apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sherlock-metrics
  namespace: sherlock
  labels:
    monitoring: apps
spec:
  selector:
    matchLabels:
      app: sherlock-metrics
  endpoints:
    - port: http-metrics
